# Each item in an area list is an area. Areas have parameters you may tweak, and will be used when loading the area list.
# Start each area item with a - (and only the area item, for every other parameter use spaces)
# List each key: value pair in a new line. If you wish to use a default value for a key, do not include the key in the area item.
# Yes, this has a lot of introductory text. This is because areas have lots of parameters that can be tweaked.
# If you want to go to the actual areas part, scroll beyond all the text that starts with #.

# ----------
# Parameters
# ----------
# *area: Name of the area.
# *background: Default background of the area.
# *afk_delay: If a positive number, the number of seconds that must pass to mark an inactive player as AFK and kick them to `afk_sendto`. If 0, no such AFK kicks take place.
# *afk_sendto: The ID of the area to kick an AFK player to.
# *background_tod: Backgrounds per time of day.
# *bglock: If false, only moderators can lock the area background; if true, no one can lock it.
# *bullet: If false, only GM+ can send IC messages with bullets/shouts. If true, no such restriction is imposed.
# *cbg_allowed: If false, only GM+ can set the area's background to one not in the hub's list. If true, no such restriction is imposed.
# *change_reachability_allowed: If false, only GM+ may /unilock or /bilock passages affecting this area. If true, no such restriction is imposed.
# *default_description: Output of /look in the area if no custom description is in place via /look_set
# *evidence_mod: Unused (do not include)
# *gm_iclock_allowed: If false, only CM+ may /iclock the area. If true, GMs may also /iclock.
# *iniswap_allowed: If true, everyone can send IC messages while iniswapped/iniedited; if false, no one can send IC messages while iniswapped/iniedited.
# *global_allowed: If false, only CM+ may use /g in the area. If true, anyone can use it.
# *has_lights: If false, the area cannot have its lights turned off via /light or similar. If true, no such restriction is imposed.
# *lobby_area: If true, the area is marked as lobby (which disallows non-GMs+ from sneaking or /knock'ing from or to the area). If false, no such restriction is placed.
# *locking_allowed: If false, everyone can lock the area; if true, no one can lock it.
# *private_area: If true, the area is marked as private (which disallows everyone from sneaking and GMs+ reading /whisper messages).
# *reachable_areas: If <ALL>, a passage will be created from this area to every other area. If it is a comma-separated list of areas (by name), a passage will be created from this area only to the listed areas.
# *restricted_chars: If a list of folder names, it prevents non-GMs using said characters from joining the area, and prompts them to choose another one if they are kicked to the area, they attempt to switch to that character while in the area, or their character is marked as restricted while they are in the area.
# *rollp_allowed: If false, only GM+ may /rollp. If true, everyone can /rollp.
# *rp_getarea_allowed: If false, only GM+ can /getarea and similar. If true, no such restriction is imposed.
# *rp_getareas_allowed: If false, only GM+ can /getareas and similar. If true, no such restriction is imposed.
# *scream_range: If <ALL>, all areas can receive a /scream message sent from this area. If <REACHABLE_AREAS>, all areas defined in reachable_areas can receive a /scream message sent from this area. If it is a comma-separated list of areas (by name), only said areas can receive /scream messages.
# *song_switch_allowed: If false, only GM+ can do /play. If true, no such restriction is imposed.
# *visible_areas: If <ALL>, a passage will be set as visible (but not necessarily reachable) from this area to every other area. If <REACHABLE_AREAS>, the procedure will be done to exactly all areas described in the areas' `reachable_areas` key. If it is a comma-separated list of areas (by name), the procedure will be done to the listed areas.

# --------
# Mandatory parameters (the area list will not load if a section does not contain the following)
# --------
# area
# background

# --------
# Optional parameters and their default values (will be assumed if not present)
# --------
#
# afk_delay: 0
# afk_sendto: 0
# background_tod: NONE
# bglock: false
# bullet: true
# cbg_allowed: false
# change_reachability_allowed: true
# default_description: `default_area_description` in config.yaml
# evidence_mod: FFA
# gm_iclock_allowed: true
# global_allowed: true
# has_lights: true
# iniswap_allowed: false
# lobby_area: false
# locking_allowed: false
# private_area: false
# reachable_areas: <ALL>
# restricted_chars: NO RESTRICTED CHARACTERS
# rollp_allowed: true
# rp_getarea_allowed: true
# rp_getareas_allowed: true
# scream_range: NO AREAS OTHER THAN THIS ONE
# song_switch_allowed: false
# visible_areas: <REACHABLE_AREAS>

- area: Lobby
  background: ReLapse/foyer
  reachable_areas: Mock Trial Room, Testing Room, Game Room, Chatroom 1, Chatroom 2, Chatroom 3, Shitposting, Mod Discussion Room
  default_description: Dare you open the box?
  rp_getareas_allowed: true
  locking_allowed: false
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: true
  bullet: false
  cbg_allowed: false
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: Mock Trial Room, Testing Room, Game Room, Chatroom 1, Chatroom 2, Chatroom 3, Shitposting
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Mock Trial Room
  background: RigMor/trialroom_insession
  reachable_areas: Lobby, Testing Room, Game Room, Chatroom 1, Chatroom 2, Chatroom 3, Shitposting
  default_description: Whodunnit?
  rp_getareas_allowed: true
  locking_allowed: false
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: true
  bullet: true
  cbg_allowed: false
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Testing Room
  background: ReLapse/testing
  reachable_areas: Lobby, Mock Trial Room, Game Room, Chatroom 1, Chatroom 2, Chatroom 3, Shitposting
  default_description: It's not unpossible... isn't it?
  rp_getareas_allowed: true
  locking_allowed: false
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: true
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Game Room
  background: RigMor/gameroom
  reachable_areas: Lobby, Mock Trial Room, Testing Room, Chatroom 1, Chatroom 2, Chatroom 3, Shitposting
  default_description: Have a little fun. As a treat.
  rp_getareas_allowed: true
  locking_allowed: false
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: false
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Chatroom 1
  background: ReLapse/roomcl
  reachable_areas: Lobby, Mock Trial Room, Testing Room, Game Room, Chatroom 2, Chatroom 3, Shitposting
  default_description: A Room for Chatting
  rp_getareas_allowed: true
  locking_allowed: true
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: false
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Chatroom 2
  background: ReLapse/roomfs
  reachable_areas: Lobby, Mock Trial Room, Testing Room, Game Room, Chatroom 1, Chatroom 3, Shitposting
  default_description: A Room for Chatting
  rp_getareas_allowed: true
  locking_allowed: true
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: false
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Chatroom 3
  background: ReLapse/roompe
  reachable_areas: Lobby, Mock Trial Room, Testing Room, Game Room, Chatroom 1, Chatroom 2, Shitposting
  default_description: A Room for Chatting
  rp_getareas_allowed: true
  locking_allowed: true
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: false
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Shitposting
  background: RigMor/exorcismroom
  reachable_areas: Lobby, Mock Trial Room, Testing Room, Game Room, Chatroom 1, Chatroom 2, Chatroom 3
  default_description: For when you just wanna be really fucking annoying.
  rp_getareas_allowed: true
  locking_allowed: false
  lobby_area: false
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: true
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true
- area: Mod Discussion Room
  background: ReLapse/testing
  reachable_areas: Lobby, Mock Trial Room, Testing Room, Game Room, Chatroom 1, Chatroom 2, Chatroom 3, Shitposting
  default_description: You're probably wondering why I've gathered you all here today.
  rp_getareas_allowed: true
  locking_allowed: false
  lobby_area: true
  private_area: false
  afk_delay: 0
  afk_sentto: 0
  bglock: false
  bullet: false
  cbg_allowed: true
  change_reachability_allowed: false
  gm_iclock_allowed: true
  iniswap_allowed: true
  global_allowed: true
  has_lights: true
  visible_areas: <REACHABLE_AREAS>
  restricted_chars: ''
  rollp_allowed: true
  rp_getarea_allowed: true
  song_switch_allowed: true