# List your character folder names, one per line.
# Start each line with -
# DR1
- Makota_HD
- Aoi_HD
- Byakuya_HD
- Celestia_HD
- Chihiro_HD
- Hifumi_HD
- Junko_HD
- Kiyotaka_HD
- Kyoko_HD
- Leon_HD
- Mondo_HD
- Mukuro_HD
- Sakura_HD
- Sayaka_HD
- Toko_HD
- Yasuhiro_HD
- AlterEgo_HD
- JunkoMM_HD
- Monokuma_HD
# DR2
- Hajime_HD
- Akane Owari_HD
- Byakuya2_HD
- Chiaki_HD
- Fuyuhiko_HD
- Gundham_HD
- Hiyoko_HD
- Ibuki_HD
- Kazuichi_HD
- Mahiru_HD
- Mikan_HD
- Nagito_HD
- Nekomaru_HD
- Peko_HD
- Sonia_HD
- Teruteru_HD
- Usami_HD
# DRV3
- Kaede Akamatsu_HD
- Shuichi Saihara_HD
- Angie_HD
- Gonta_HD
- Himiko_HD
- Kiibo_HD
- Kaito_HD
- Kirumi_HD
- Kokichi_HD
- Korekiyo_HD
- Maki Harukawa_HD
- Miu Iruma_HD
- Rantaro_HD
- Ryoma_HD
- Tenko_HD
- Tsumugi_HD
- Monodam_HD
- Monophanie_HD
- Monokid_HD
- Monosuke_HD
- Monotaro_HD
# YTTD
- Sara Chidouin
- Joe Tazuna
- Keiji Shinogi
- Kanna Kizuchi
- Q-taro Burgerberg
- Sou Hiyori
- Reko Yabusame
- Nao Egokoro
- Kai Satou
- Gin Ibushi
- Kazumi Mishima
- Alice Yabusame
- Ranmaru Kageyama
- Hinako Mishuku
- Naomichi Kurumada
- Mai Tsurugi
- Anzu Kinashi
- Shunsuke Hayasaka
- Kugie Kizuchi
- Megumi Sasahara
- Sue Miley
- Rio Ranger
- Tia Safalin
- Gashu
- Midori
- Meister
# DRA
- Yuki MaedaA1_HD
- Akane Taira_HD
- Ayama Hatano_HD
- Haruhiko Kobashikawa_HD
- Kakeru Yamaguchi_HD
- Kanata Inori_HD
- Kinji Uehara_HD
- Kiyoka Maki_HD
- Kizuna Tomori_HD
- Mikako Kurokawa_HD
- Mitsuhiro Higa_HD
- Rei Mekaru_Y_HD
- Satsuki Iranami_HD
- Teruya OtoriA1_HD
- Tsurugi Kinjou_HD
- Kisaragi Yamato_HD
# SDRA2
- Sora_HD
- Emma_HD
- Hajime Makunouchii_HD
- Hibiki_HD
- Iroha_HD
- Kokoro_HD
- Mikado Sannoji_HD
- Nikei_HD
- Setsuka Chiebukuro_HD
- Shinji_HD
- Hashimoto_HD
- Teruya_HD
- Yoruko_HD
- Maeda_HD
- Yuri Kagarin_HD
- Monocrow_HD
# Eden's Garden
- Damon Maitsu
- Cassidy Amber
- Desmond Hall
- Diana Venicia
- Eloise Taulner
- Eva Tsunaka
- Grace Madison
- Ingrid Grimwall
- Jean DeLamer
- Jett Dawson
- Kai Monteago
- Mark Berskii
- Toshiko Kayura
- Ulysses Wilhelm
- Wenona
- Wolfgang Akire
- Tozu
- Mara
# Lapse
- Echo Pine_HD
- Art Campiopiano_HD
- Ashley Westbridge_HD
- Cyrus Suryc_HD
- Forte Solo_HD
- Kanon Ota_HD
- Lyle Termina_HD
- Missy Vesper_HD
- Pandora Espere_HD
- Sei Konno_HD
- Akihiko_Quartz_HD
- Gaea Espere_HD
# OCs
- Amunet_LeBeau_HD
- Darling_Brind-Ivory_HD
- Silva_Prower_HD
- Rowan_Maximon_HD
- Mercy_Mun_HD
- Cecilia_Marino_HD
- Claudia_Sandall_1.7
- Karmen Hernandez
- Nyanlathotep
- Jennifer Gale_PN
- QueeninYellow
- Eleanor Hayes
- Dee
- Aiyana_Hood
- Aiyana_Shaman